create view Vw_Tradings as
select
		Id,
		Stage,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, CreatedAt, 1)), '-03:00') CreatedAt,
		HoldAsset,
		TradeAsset,
		BuyOrderQuoteQty,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, BuyOrderCreatedAt, 1)), '-03:00') BuyOrderCreatedAt,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, BuyOrderFilledAt, 1)), '-03:00') BuyOrderFilledAt,
		BuyPrice,
		BuyOrderFee,
		TradeAssetQty,
		SellPrice,
		SellStopLimitPrice,
		RollbackPrice,
		UpgradePrice,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, SellOrderCreatedAt, 1)), '-03:00') SellOrderCreatedAt,
		SellOrderFee,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, SellOrderLastReadAt, 1)), '-03:00') SellOrderLastReadAt,
		MinPriceRead,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, MinPriceReadAt, 1)), '-03:00') MinPriceReadAt,
		MaxPriceRead,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, MaxPriceReadAt, 1)), '-03:00') MaxPriceReadAt,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, SellOrderFilledAt, 1)), '-03:00') SellOrderFilledAt,
		SellOrderExecutedPrice,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, CompletedAt, 1)), '-03:00') CompletedAt,
		todatetimeoffset(dateadd(hour, -3, convert(datetime2, UpdatedAt, 1)), '-03:00') UpdatedAt,
		SellOrderKind,
		IsRollback,
		ProcessId,
		Active
	from Tradings